apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
data:
  haproxy.cfg: |
    global
        log stdout format raw local0
    defaults
        log global
        mode http
        timeout connect 5000ms
        timeout client 50000ms
        timeout server 50000ms
    frontend http-in
        bind *:80
        default_backend tomcat-backend
    backend tomcat-backend
        balance roundrobin
        # Service Discovery: Using the internal service name
        server tomcat-1 tomcat-service:8080 check